server:
  port: 9911
  servlet:
    context-path: /crm


mybatis:
  mapper-locations: /mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true   # 将表的字段与实体类的属性相对应(转成驼峰命名)

spring:
  # mysql配置
  # 本地
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true&&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 测试
    #url: jdbc:mysql://47.114.140.213:3306/crm?useUnicode=true&&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    #password: "@LDYroot123"
    #username: maplemysql
    #driver-class-name: com.mysql.cj.jdbc.Driver

    # 生产
    #url: jdbc:mysql://47.96.230.123:3306/crm?useUnicode=true&&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    #password: "@LDYroot123"
    #username: maplemysql
    #driver-class-name: com.mysql.cj.jdbc.Driver

  # redis配置   https://blog.csdn.net/u010957645/article/details/89340983?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase
  redis:
    database: 0                      # Redis数据库索引（默认为0）
    host: localhost                  # Redis服务器地址
    port: 6379                       # Redis服务器连接端口
    password:                   # 密码(因为我本机未设密码，因此为空)
    lettuce:
      pool:
        max-active: 20               # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1                 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10                 # 连接池中的最大空闲连接
        min-idle: 0                  # 连接池中的最小空闲连接
    timeout: 2000                    # 连接超时时间（毫秒）